name: CI testing
on:
  push:
    branches:
        - main

jobs:
  hello-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Print greeting
        run: echo "Hello, CI with GitHub Actions!"
