name: Self-Hosted Runner Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted   # or add more labels if you set them
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Run unit tests
        run: python -m unittest discover -v
