name: Self-Hosted Runner Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Run unit tests
        run: python3.9 -m unittest discover -v
